services:
  postgres:
    container_name: makerhub-postgres 
    image: pgvector/pgvector:pg15
    restart: no
    environment:
      POSTGRES_USER: makerhub
      POSTGRES_PASSWORD: makerhub
      POSTGRES_DB: db_makerhub
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U makerhub -d db_makerhub"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: makerhub-minio
    restart: no
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - makerhub-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: makerhub-mailpit
    ports:
      - "${MAILPIT_SMTP_PORT}:1025"
      - "${MAILPIT_UI_PORT}:8025"
    environment:
      - MP_MAX_MESSAGES=${MAILPIT_MAX_MESSAGES}
      - MP_SMTP_AUTH_ACCEPT_ANY=${MAILPIT_SMTP_AUTH_ACCEPT_ANY}
    volumes:
      - mailpit_data:/var/lib/mailpit/data

volumes:
  postgres_data:
  mailpit_data:
  minio_data:

networks:
  makerhub-network:
    driver: bridge
